### ISSUE TITLE
Freecam issues

### ISSUE THREAD

**Issue by Flourick** [Flourick/FVT-fabric#10]
boat controllable client side, horse can jump, items can be swapped/dropped, update BL in HUD info while in freecam

**Comment by jtenner** [comment]
Wurst allows you to free place while in free cam. Would it be possible to add this back in? It's super helpful with scaffolding and placing blocks beneath a block I'm standing on to staircase downward.

**Comment by Flourick** [comment]
I actually thought about that but atleast for me it feels way too cheaty. Freecam is meant to be a tool to explore surroudings not make you place blocks or open chests you otherwise could not.
