### ISSUE TITLE
Game Crashes when using freecam

### ISSUE THREAD

**Issue by SniperPickAxe** [Flourick/FVT-fabric#110]
For a while I've been getting this bug.
The error happens when ever I use free cam from key binds. No other mods are used, but it usually fixes after around 5-10 minutes or after I go through a portal, allowing me to use free cam again. . In 1.19, This didn't work. It may have something to do with processing power as I had other programs open.
[crash-2022-06-28_15.48.24-client.txt](https://github.com/Flourick/FVT-fabric/files/8998048/crash-2022-06-28_15.48.24-client.txt)

**Comment by Flourick** [comment]
I can't seem to replicate the issue, even on my AMD notebook it works fine, can you try the attached version? I did fix something related to freecam there.
[fvt-fabric-1.11.1-mc1.19.tar.gz](https://github.com/Flourick/FVT-fabric/files/8999615/fvt-fabric-1.11.1-mc1.19.tar.gz)

**Comment by SniperPickAxe** [comment]
I do not have time to replicate tonight, but tomorrow (approx. 8-10h) I will try to replicate on the new version. If I can replicate it, I will try to screen record it. And reply again to this thread (approx. 19h) From: FlourickSent: Tuesday, 28 June 2022 7:27 PMTo: Flourick/FVT-fabricCc: SniperPickAxe; AuthorSubject: Re: [Flourick/FVT-fabric] Game Crashes when using freecam (Issue #110) I can't seem to replicate the issue, even on my AMD notebook it works fine, can you try the attached version? I did fix something related to freecam there.fvt-fabric-1.11.1-mc1.19.tar.gz—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by JairusSW** [comment]
I get the exact same thing

**Comment by Flourick** [comment]
Even with the version attached above?

**Comment by Flourick** [comment]
Also does this happen both in singleplayer and multiplayer?

**Comment by JairusSW** [comment]
@Flourick, I didn't try yet. It crashes with the latest version on modrinth though

**Comment by SniperPickAxe** [comment]
I tried the version you linked.The crash does not happen all the time, so this may be a fluke.It worked in Singleplayer 1 time, it takes forever to load a world for me so I’m not testing further. In previous versions it crashed.It worked in multiplayer.It worked in realms.If it crashes again, I’ll let you know.Btw, why did you remove auto reconnect in the latest version, It was the main reason one of the main reasons I use FVTWhile I’m at it, is it possible to make auto attack not hit iron golems and villagers? Its rather annoying when I don’t realise its on and I die to a golem in 1 hit.FYI the version you linked is not on the releases list. The latest version there is 1.11.0, not 1.11.1
