### ISSUE TITLE
Game crashes on startup

### ISSUE THREAD

**Issue by Xoouu** [Flourick/FVT-fabric#116]
Here is the crash log: https://pastebin.com/LtCgAtyk

FVT 1.12.0 worked fine.

**Comment by Flourick** [comment]
Remove More Chat History mod as FVT now does that aswell.

**Comment by Xoouu** [comment]
It is working now! Thank you for the fast answer, probably should have read the changelog xD.

**Comment by Flourick** [comment]
No problemo
