### ISSUE TITLE
Mod compatibility with Inventorio

### ISSUE THREAD

**Issue by aMazeInRunar** [Flourick/FVT-fabric#119]
Theres this other mod called inventorio and it adds some stuff with the hot bar and inventory and that completely breaks this mod. I don't know if this is something easy to fix or not but just letting you know in case you were interested =) 
https://github.com/Lizard-Of-Oz/Inventorio

**Comment by aMazeInRunar** [comment]
This issue is in 1.19 btw, idk if thats important

**Comment by Flourick** [comment]
Just 1.19? And what mod versions?

**Comment by Flourick** [comment]
A'right, thanks. I'll take a look.

**Comment by aMazeInRunar** [comment]
Thank you very much :>

**Comment by Flourick** [comment]
Too many conflicts, not really fixable.
