### ISSUE TITLE
Add an Autocrafting feature

### ISSUE THREAD

**Issue by Flourick** [Flourick/FVT-fabric#12]
a big one, basically select a recipe to automatically craft and once it's possible will automatically commence crafting or via a button in inventory/crafting bench.

**Comment by jtenner** [comment]
Ctrl + shift + alt + click on a recipe to craft up to 64 and toss them out onto the floor.

That's my vote because of gold crafting.

**Comment by Flourick** [comment]
This will not be worked on for some time as it's a rather big feature and I haven't really thought how to approach it either.

**Comment by jtenner** [comment]
https://github.com/811Alex/Quickcraft/

**Comment by Flourick** [comment]
That seems like an easy way to do actually.

**Comment by Flourick** [comment]
Reverted changes as I can't have a feature that only works "sometimes".
