### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by ManInMyVan** [Flourick/FVT-fabric#121]
pastebin.com/NxSE750j

**Comment by Flourick** [comment]
You use a lot of mods but I think it might be that Quilt is not compatible will test when I get the chance.

**Comment by Flourick** [comment]
It works fine on Quilt. Try removing mods and see when it stops working.

**Comment by ManInMyVan** [comment]
[MoreChatHistory](modrinth.com/mod/morechathistory)

**Comment by Flourick** [comment]
Makes sense as FVT already does that.
