### ISSUE TITLE
Feature: Auto Attack have option to stop on near starvation

### ISSUE THREAD

**Issue by JairusSW** [Flourick/FVT-fabric#122]
@Flourick, would it be an option to add a feature so that auto attack stops when the player is about to starve?

**Comment by Flourick** [comment]
That's why AutoEat is a thing so you can have food in your offhand.

**Comment by JairusSW** [comment]
What if you don't have infinite food?

**Comment by JairusSW** [comment]
The idea is that you would be able to set how long you afk by placing x amount of food in your offhand giving x amount of afk time

**Comment by Flourick** [comment]
That seems like an unnecessary complication.
