### ISSUE TITLE
Autototem

### ISSUE THREAD

**Issue by stritzs** [Flourick/FVT-fabric#123]
Hello! I love your mod, but there's an issue with your autototem. The mod puts the totem on your cursor if you open your inventory, but it doesn't put the totem into your offhand. I've died at farms from hunger multiple times, and died in battles because of this. Is there a fix to this? I know I could just use offhand autoeat, but I can't do that for fighting because that would put me at risk of death.

**Comment by Flourick** [comment]
It does not put the totem into your offhand unless you already have a totem in your offhand. It just replaces the consumed one for a new one from your inventory.

**Comment by stritzs** [comment]
You didn't read my issue correctly. I'll have a totem in my offhand, but it doesn't get replaced when I pop one. I have to open my inventory and all the module does is put the totem on my cursor. I shouldn't have to open my inventory for autototem, it should just replace it. I know how autototem works. This mod doesn't work.

**Comment by Flourick** [comment]
What mod version do you use? It works fine for me on the latest one. And are you using any other mods that move stuff around like Mouse Tweaks or similar.
