### ISSUE TITLE
release for 1.19.3

### ISSUE THREAD

**Issue by jamesiee** [Flourick/FVT-fabric#127]
hello please can you release the fvt fabric for 1.19.3 as I don't know how to put the files together to make it a mod.

many thanks,
jamesiee

**Comment by xl1533** [comment]
This may help you.
[fvt-fabric-1.14.0-mc1.19.3.zip](https://github.com/Flourick/FVT-fabric/files/10253425/fvt-fabric-1.14.0-mc1.19.3.zip)

**Comment by Flourick** [comment]
I kinda forgot to release it, will do soon.

**Comment by jamesiee** [comment]
> 

thank you
