### ISSUE TITLE
Turn off freecam damage to first person?

### ISSUE THREAD

**Issue by Jeppelelle** [Flourick/FVT-fabric#133]
Hi!

When did this change: https://github.com/Flourick/FVT-fabric/blob/ce9c601dae82bf1e9aa960e4b620b00125f08f1b/src/main/java/me/flourick/fvt/mixin/ClientPlayerEntityMixin.java#L97

I have used FVT for a long time and it did not used to yeet me back to first person view if i take damage while in freecam or run out of hunger while in freecam

And i don't see an option to turn it off in the FVT settings? It is kinda annoying since i want to inspect my farms while using them, like a raid farm, but it's impossible since i have 0.000000000ms before i get forced into first person perspective again

So, how do i disable this so i can fly around in freecam even when taking damage?

**Comment by Flourick** [comment]
I can make it optional, sure

**Comment by Jeppelelle** [comment]
That would be awesome 👍

(And thanks for making a great mod 👍)
