### ISSUE TITLE
Server-side disabler

### ISSUE THREAD

**Issue by JeffAxe123** [Flourick/FVT-fabric#17]
Please could you make a server-side mod to pear with this that disables configurable features like auto-totem ect. Otherwise this is to much of a hack client.

**Comment by Flourick** [comment]
I know that some features such as AutoTotem, Freecam, Triggerbot and well, to an extent everything this mod offers gives you an advantage over others but that's what this mod is basically for, making the gameplay easier and tweaking some things that were annoying to me while playing. Also this is supposed to be purely client-side mod so wouldn't make much sense to have a server side.
