### ISSUE TITLE
auto-hit makes me hit mobs i dont want to hit

### ISSUE THREAD

**Issue by AlexTheDolphin0** [Flourick/FVT-fabric#19]
I turn it on and it works fine. I just have one problem. My sword is attacking my wolf now and its dead, and it keeps killing my snow golem turrets. I think there should be a way to whitelist mobs from being hit

**Comment by Flourick** [comment]
In a way that's intended as it's not meant to be a cheat but only aid in AFK farms, such as gold farms. But I might add a player/mob toggle at some point.
