### ISSUE TITLE
Freecam glow causes my glow to always be green.

### ISSUE THREAD

**Issue by Johnnycyan** [Flourick/FVT-fabric#21]
Freecam causing my character to glow green makes it so when I have the glowing effect from any source I glow green instead of the appropriate color. The reason this was noticeable is because I play on a server that allows you to get glows in specific colors but instead I was always green until disabling this mod. Solution I assume would be setting my "team" back to what it was before freecam was enabled whenever freecam is disabled since that's what changes the color.

**Comment by Flourick** [comment]
Fixed, now it should only glow green while in freecam.
