### ISSUE TITLE
Suggestion: Disabling mod button in options menu

### ISSUE THREAD

**Issue by epic0421** [Flourick/FVT-fabric#22]
I would like to see an option to disable the mod button in the options menu because it conflicts with where the physics mod puts their button.
![image](https://user-images.githubusercontent.com/85042398/128444690-03bd17aa-62af-4e71-a1e9-976f3813342f.png)

**Comment by epic0421** [comment]
Also want to suggest adding a keybind to open the config menu

**Comment by Flourick** [comment]
I was thinking about this but if someone is not using ModMenu there would be no other way for them to open the menu if they disable the button. Maybe I could add a fourth option to move it into a corner.

**Comment by Flourick** [comment]
also yeah, keybind is not a bad idea either
