### ISSUE TITLE
Add option to disable chest store/drop/get all buttons

### ISSUE THREAD

**Issue by Timolino456** [Flourick/FVT-fabric#23]
this is driving me crazy lol
I actually prefer the chest/inventory sorting buttons of another mod to these, so a config option to disable or have them somewhere else would be much appreciated
![image](https://user-images.githubusercontent.com/38137599/130318896-d372eba0-1373-43f0-aecb-8741bb5e5b3f.png)

**Comment by Flourick** [comment]
fair enough, I'll add an option for that
