### ISSUE TITLE
[crash] fvt crashes game after update at startup, probably interfering with other mods

### ISSUE THREAD

**Issue by TobiPeterG** [Flourick/FVT-fabric#31]
Here's the log:
[crash-2021-09-05_14.04.16-client.txt](https://github.com/Flourick/FVT-fabric/files/7111542/crash-2021-09-05_14.04.16-client.txt)

With version 1.7.0, this crash did not occur

**Comment by Flourick** [comment]
Seems like sodium-extra is not compatible, I'll look into that

**Comment by TobiPeterG** [comment]
Umm that's interesting, the game still crashes, but now it seems like an incompatibility with charm.
[crash-2021-09-05_17.10.48-client.txt](https://github.com/Flourick/FVT-fabric/files/7111872/crash-2021-09-05_17.10.48-client.txt)

Let me remove charm to see if there are other incompatible mods

**Comment by Flourick** [comment]
A'right, fixed Charm aswell

**Comment by TobiPeterG** [comment]
> A'right, fixed Charm aswell

Thank you very much! :)
