### ISSUE TITLE
Suggestion: Prevent Player Entity from being hit by Trigger Bot.

### ISSUE THREAD

**Issue by 0xBit-MC** [Flourick/FVT-fabric#32]
I was curious if it would be possible for you to write a function to remove Player Entity from being hit by Trigger Bot because there is a lot of kiddos using this mod as a "hack" for PvP Clients. Most of them are incapable of changing the code themselves.

**Comment by Flourick** [comment]
Yeah, I'll exclude players from trigger bot, it's meant for AFK farming anyway and not PvP.
