### ISSUE TITLE
Continuity failing to reload any resource pack with FVT

### ISSUE THREAD

**Issue by Andrix03** [Flourick/FVT-fabric#38]
Here is a video showcasing the issue:

https://youtu.be/Gs0Otaf92nI 

Basically It creates an endless loop of loading until it stops with an error message "Resource reload failed".
Without the mod FVT solves every issue.

**Comment by Flourick** [comment]
Video is private, what mods do you use?

**Comment by Andrix03** [comment]
Sorry, i'm going to fix it

**Comment by Flourick** [comment]
Go to your logs and post the latest one where you crash on pastebin or here, there should be some error just repeating.

**Comment by Andrix03** [comment]
[latest.log](https://github.com/Flourick/FVT-fabric/files/7238865/latest.log)

There you go
