### ISSUE TITLE
Incompatible with carpet mod's flexible block placement

### ISSUE THREAD

**Issue by erxson** [Flourick/FVT-fabric#60]
When im trying to use flexible block placement in carpet, it doesn't work. 
Mod list:
Fabric Api
FVT
Carpet Mod

**Comment by Flourick** [comment]
I don't see Carpet having that feature, you sure it is the right mod?

**Comment by erxson** [comment]
> I don't see Carpet having that feature, you sure it is the right mod?

yes

https://www.youtube.com/watch?v=xWEvcfzCPIs

**Comment by Flourick** [comment]
That is Tweakeroo, but eh whatever, I'll take a look.

**Comment by erxson** [comment]
> That is Tweakeroo, but eh whatever, I'll take a look.

My bad

**Comment by Flourick** [comment]
Tweakeroo is not updated to 1.18.1 yet so I'll wait then look into it.

**Comment by erxson** [comment]
https://github.com/adryd325/tweakeroo 1.18 fork

**Comment by Paradox-77** [comment]
Masa pushed an update today for Tweakeroo which has support for 1.18.1. 
[Tweakeroo Files](https://www.curseforge.com/minecraft/mc-mods/tweakeroo/files)
But unfortunately, the GitHub Repo doesn't seem to be updated.

**Comment by Flourick** [comment]
Nice, will check it out.
