### ISSUE TITLE
Crash on Launch. Incompatibility with Notify mod.

### ISSUE THREAD

**Issue by TalEdd** [Flourick/FVT-fabric#68]
[crash-2021-12-08_14.23.37-client.txt](https://github.com/Flourick/FVT-fabric/files/7673828/crash-2021-12-08_14.23.37-client.txt)
[crash-2021-12-08_14.23.36-server.txt](https://github.com/Flourick/FVT-fabric/files/7673829/crash-2021-12-08_14.23.36-server.txt)

**Comment by Flourick** [comment]
Now that's a lot of mods, but this does not look like a compatibility issue, just me forgot to null check.
