### ISSUE TITLE
Freecam broken

### ISSUE THREAD

**Issue by SystematicError** [Flourick/FVT-fabric#74]
Hello, I'm submitting a bug report regarding the freecam ability in this mod. Previously in 1.17, freecam works perfectly, however, on 1.18 it seems to be stuck inside the players head. This issue was able to be reproduced on another install of minecraft too.

**OS:** `Linux`
**Minecraft Version:** `1.18.1`
**Fabric Version:** `0.12.11`
**Fabric API Version:** `0.44.0+1,18`
**Java Version:** `17.0.1`
**FVT Version:** `1.9.0-mc1.18.1`

**Installed Mods:** `Fabric API` `FerriteCore` `Flour's Various Tweaks` `Hydrogen` `Immersive Portals` `LambDynamicLights` `LazyDFU` `Lithium` `Logical Zoom` `Mod Menu` `Sodium` `Starlight`

**Comment by Flourick** [comment]
Could not reproduce, can you post the exact mod versions you use?

**Comment by Catto-Got-That-Hatto** [comment]
Hello, I've got the exact same issue. It seems that it is caused by the [Immersive portals](https://modrinth.com/mod/immersiveportals) (1.1.4) mod, removing the mod seems to have solved the freecam issue.

**Comment by SystematicError** [comment]
![image](https://user-images.githubusercontent.com/63366086/146483512-44b5397f-d310-4993-ae42-c048805e755d.png)

Here are my mod versions, some stuff is bleeding edge and built from source

**Comment by Flourick** [comment]
Yes, the problem is with Immersive Portals v1.1.4 alone.

**Comment by Flourick** [comment]
Not easily fixable
