### ISSUE TITLE
Fix Horse Stats Feature

### ISSUE THREAD

**Issue by MadDog443** [Flourick/FVT-fabric#77]
Please make it possible to view horse stats without having to first tame the horse. This would save players a lot more time.

**Comment by Flourick** [comment]
Agreed

**Comment by MadDog443** [comment]
Thank you. Btw if you are ever looking for inspiration for new features, check out the CivCraft mods that were used for servers like CivClassic, CivRealms, etc. Some crazy stuff. References would be:

**[Synapse](https://github.com/Gjum/Synapse) & Axon:** Painted a ring around visible player nametags, would color nametags based on designation as friendly, neutral or enemy, could relay player coords to other players via a private server
**[CombatRadar](https://github.com/Aleksey-Terzi/CombatRadar) / [CivRadar](https://github.com/CivcraftMods/CivRadar):** Radar for playernames only
**Civ Mining Counter:** output stats of mining based on biomes to give estimated mining rates for ores per biome
**[Health bar](https://www.curseforge.com/minecraft/mc-mods/health-bar):** Displayed exact info about your health wherever you wanted on the screen
**Enderpearl timer:** Countdown for when you could throw another ender pearl.
**Auto-replant:** Auto-replanted crops you broke and stopped you from breaking them again. EXP was gained via crops so it was worth it.
**SkyNet:** Alerts for join/leave traffic, could be set to only notify of specific players.

**Comment by MadDog443** [comment]
_Oh shiiiit_
