### ISSUE TITLE
Auto attack while being in the menu

### ISSUE THREAD

**Issue by momokinou** [Flourick/FVT-fabric#83]
Hi, thank you for your work.

Is it possible to enable the auto attack while being in the echap menu?
It's useful for multiplayer.

(This menu)
![image](https://user-images.githubusercontent.com/31689903/151671663-32efd20c-45eb-43be-a6aa-cf2cfcfc8a8e.png)

Thanks in advance :D

**Comment by momokinou** [comment]
And, is it possible to edit the delay between each attack? because on server with 1.8 pvp, it can be useful.

**Comment by Flourick** [comment]
It's not made for newest versions only and it's intentional that it does not work in the menu as it makes no sense if it did, it's supposed to "pause" the game.

**Comment by Flourick** [comment]
No, it's automatic
