### ISSUE TITLE
Option to disable villager trade tweak

### ISSUE THREAD

**Issue by Vitamoon** [Flourick/FVT-fabric#92]
Hi there! I also use [EasierVillagerTrading](https://www.curseforge.com/minecraft/mc-mods/easiervillagertrading) and occasionally the shift-click to autotrade feature conflicts (especially when there is one item). Would it be possible to add an option to turn this off?

Thanks in advance!

**Comment by Flourick** [comment]
Sure, I'll add the toggle for that.
