### ISSUE TITLE
Compatibility with DynamicCrosshair

### ISSUE THREAD

**Issue by Crendgrim** [Flourick/FVT-fabric#96]
I have received a crash report for my mod "DynamicCrosshair" when used in conjunction with FVT, see: https://github.com/Crendgrim/DynamicCrosshair/issues/11

This happens because we are both redirecting the exact same call to render the crosshair.

For the time being, I have circumvented the crash by simply marking my mixin as non-required. This limits my mod's functionality massively, and disables the arguably more interesting part of it.
Therefore, ideally I'd like to add "proper" compatibility, as I see no reason our mods couldn't augment each other.

I see two solutions to how this could be set up:
1. From looking at what your mixin does, I believe I could replicate that in DynamicCrosshair with a dynamically loaded compatibility helper that would then reference your mod's config's values. In order for that to work, my mixin would require priority, while yours would have to soft-fail (`require=0`).
2. Sadly, it seemingly is not possible to mix into methods that are mixins themselves; but it is possible to mix into methods that get added by other mixin classes (although, if I understand it right, this just happens to work and isn't officially supported either). If you were to extract the logic from a mixin method to a non-annotated one (which can still be part of the Mixin class), I could add a mixin into this method and simply redirect your `drawMatrix` call (instead of the vanilla one). This is probably the easier, if a bit hacky, solution.

Let me know your thoughts on this! Maybe you even know of another solution that I missed?

**Comment by Crendgrim** [comment]
At first I also thought it'd be out of scope, but the more I think about it, the more having a colour/size option as part of my mod makes sense to me. I already let the styles be configurable, so why not their size & colour, too? So I may just go with your option 1+2b, and adopt that feature from your mod.

**Comment by Flourick** [comment]
A'righty, that's settled then

**Comment by ardissaps** [comment]
> A'righty, that's settled then

Nice, cant wait. No hurry. :p
