### ISSUE TITLE
Update to 1.19

### ISSUE THREAD

**Issue by Flourick** [Flourick/FVT-fabric#99]
Progress thread

**Comment by Flourick** [comment]
228/228 build errors gone, 3/45 features work.

**Comment by Flourick** [comment]
8/45 features work

**Comment by Flourick** [comment]
18/45 features work

**Comment by ale6892** [comment]
Can't wait to this out! Best fabric mod out there,good job!

**Comment by Flourick** [comment]
All features work, still needs a bit of cleanup, will release this weekend.
